require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
vim.cmd("colorscheme tokyonight")
vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
require("user.highlights")
require("user.cmp")
require("user.lsp.mason")
require("user.lsp")
require("user.telescope")
require("user.gitsigns")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
